# -*- coding: utf-8 -*-
"""iris_data_visualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pL7AaIX2_xlRivzoXRqdYgACb1VzW2zg
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

iris = pd.read_csv('/content/Iris.csv.csv')
iris

iris.info()

iris.describe()

iris['Species'].unique()

iris.duplicated()

iris.duplicated().sum()

iris.isnull().sum()

iris.dtypes

iris.index

iris.shape

plt.title('Total number of Species')
sns.countplot(x = 'Species',data = iris)

sns.scatterplot(x = 'PetalLengthCm', y = 'PetalWidthCm',data = iris,hue = 'Species')

sns.scatterplot(x = 'SepalLengthCm', y = 'SepalWidthCm',data = iris,hue = 'Species')

sns.scatterplot(x = 'SepalLengthCm', y = 'PetalLengthCm',data = iris,hue = 'Species')

sns.scatterplot(x = 'SepalWidthCm', y = 'PetalWidthCm',data = iris,hue = 'Species')

sns.pairplot(iris,hue = 'Species')

features = iris.drop('Species',axis=1)
label = iris['Species']

features

label

features.corr

sns.heatmap(features.corr())

"""Observation :-
- There is no null value in this data.
- This data is a perfect data of 150 rows and 6 columns with 50-50-50 each Species.
- There is no duplicates in this data.
- Species setosa is showing clearly in this data.
- There is outliers and overlapping on Species versicolor and virginica. 

"""
cool




